In [1]:
import numpy as np

In [2]:
# tensor is an array with more than 2 dimensions

In [8]:
T = np.array([[[2, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(T)
print(T.shape)

[[[ 2  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [9]:
# transpose of a matrix
x = np.array([[1, 2], [3, 4]])
print(x)

xt = np.transpose(x)
print(xt)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [11]:
# norm of a vector - it can be thought as a proxy for size of a vector
# Lp norm = pth root of summation(abs(xi)^p)

In [12]:
# L2 norm is also known as eucledian norm calculated as xT x
# L1 norm is absolute sum of elements
# Linfinity means absolute value of the element with highest magnitude

In [15]:
x = np.array([-5, 3, 10])
lp2 = np.linalg.norm(x)           # L2 norm
print(lp2)

11.575836902790225


In [16]:
lp1 = np.linalg.norm(x, ord=1)
print(lp1)

18.0


In [17]:
lpinf = np.linalg.norm(x, ord = np.inf)
print(lpinf)

10.0


In [18]:
arr = np.array([[2, -2, 1], [-1, 2, -1], [2, -4, 1]])
print(np.linalg.norm(arr, ord = np.inf))

7.0


In [19]:
print(arr)

[[ 2 -2  1]
 [-1  2 -1]
 [ 2 -4  1]]


In [20]:
print(np.linalg.norm(arr))

6.0


In [21]:
a = np.array([[1, -3, 4], [-2, 10, -7], [0, 1, 0], [0, 0, 0]])
b = np.array([[5, 0], [-2, 11], [-3, 12]])
print(a)
print(b)

[[ 1 -3  4]
 [-2 10 -7]
 [ 0  1  0]
 [ 0  0  0]]
[[ 5  0]
 [-2 11]
 [-3 12]]


In [22]:
print(a.dot(b))

[[-1 15]
 [-9 26]
 [-2 11]
 [ 0  0]]
