In [4]:
import numpy as np

In [15]:
# creating array in numpy, by default is float64
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.dtype)

# dimensions of an array
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)


In [5]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [7]:
# creating arrays of zeros, ones and custom values
a = np.zeros((3, 3))
print(a)

b = np.ones((2, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
c = np.full((3, 2), 7)
print(c)

[[7 7]
 [7 7]
 [7 7]]


In [16]:
# identity matrix - size/square matrix
d = np.eye(4)
print(d)
print(d.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


In [10]:
# random matrix
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

[[0.46465236 0.66435526 0.4823343 ]
 [0.20026948 0.31190851 0.62680359]]


In [11]:
print(randomMatrix[ : , 1])               # means all rows of 1st column

[0.66435526 0.31190851]


In [12]:
# changing particular values of the matrix
randomMatrix[1, 1: ] = 1                # 1st row -> 1st and 2nd column
print(randomMatrix)

[[0.46465236 0.66435526 0.4823343 ]
 [0.20026948 1.         1.        ]]


In [14]:
z = np.zeros((3, 3))
print(z)

z[1, : ] = 5
z[ : , -1] = 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [18]:
# to create an int64 datatype
z = np.zeros((3, 3), dtype = np.int64)
print(z)
print(z.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [19]:
# mathematical operations
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x+y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [20]:
print(x-y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [21]:
# element wise multiplication
print(x*y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [22]:
# element wise division
print(x/y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [23]:
# element wise square root of elements
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [24]:
# matrix multiplication / dot product
print(x)
print(y)

print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [25]:
# scalar multiplication in vector (dot product)
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
# 1.1 + 2.2 + 3.3 + 4.4
print(a.dot(b))
print(np.dot(a, b))

30
30


In [26]:
print(sum(a))
print(np.sum(a))

10
10


In [27]:
print(x)

[[1 2]
 [3 4]]


In [29]:
print(np.sum(x))
print(np.sum(x, axis = 0))          # sum of elements column wise
print(np.sum(x, axis = 1))          # sum of elements row wise

10
[4 6]
[3 7]


In [30]:
# stacking of arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [31]:
np.stack((a, b), axis = 0)              # vectors stacked column wise

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [33]:
p = np.stack((a, b), axis = 1)              # vectors stacked row wise
print(p)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [36]:
p = p.reshape((2, 4))          # if we give reshape((-1, 4)) it will automatically calculate number of rows
print(p)

[[ 1  1  2  4]
 [ 3  9  4 16]]


In [37]:
p2 = p.reshape((8, ))               # linear array
print(p2)

[ 1  1  2  4  3  9  4 16]


In [40]:
a = np.arange(10)             # starts from 0 and produces 10 integers
print(a)
a = np.arange(10) + 4         # starts from 4
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12 13]


In [41]:
# random module

In [42]:
np.random.shuffle(a)
print(a)

[ 9 13  6  8 10  5  7  4 12 11]


In [43]:
# random numbers b/w 0 and 1
a = np.random.rand(2, 3)
print(a)

[[0.80364894 0.66696048 0.61451838]
 [0.36693994 0.73613553 0.28967873]]


In [44]:
# normally distributed random numbers       (Standard normal distribution)
a = np.random.randn(2, 3)
print(a)

[[-0.75821193 -0.31209804 -0.25275284]
 [-0.64392891  0.06458413 -0.68553352]]


In [48]:
# random integers between given range
a = np.random.randint(2, 7, 4)       # 4 random numbers b/w 2 and 7
print(a)

[4 6 3 4]


In [49]:
# randomly pick one element from an array
element = np.random.choice([1, 3, 45, 4, 67, 9])
print(element)

4


In [1]:
# np.random.seed(1)        # is used to set the starting state of random numbers

In [2]:
# statistics

In [5]:
a = np.array([[1, 2, 3, 4], [7, 6, 2, 0]])
print(a)
print(np.min(a))
print(np.min(a, axis = 0))       # axis = 0 means column wise minimum element

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]


In [6]:
print(np.mean(a))
print(np.mean(a, axis = 1))

3.125
[2.5  3.75]


In [7]:
b = np.array([1, 2, 3, 4, 5])
print(sum(b)/5)
print(np.mean(b))

3.0
3.0


In [8]:
c = np.array([1, 5, 4, 2, 0])
print(np.median(c))

2.0


In [9]:
# mean vs average
# mean is sum of all elements by total elements whereas average is weighted mean
w = np.array([1, 2, 3, 4, 5])
print(np.average(c, weights = w))

2.066666666666667


In [11]:
# standard deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

print(np.std(c))

1.854723699099141
1.854723699099141


In [12]:
# variance
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
